### PR TITLE
add additional CNCF projects

### PR DESCRIPTION
**Pull request by xmulligan**
Signed-off-by: Bill Mulligan <billmulligan516@gmail.com>

### CODE REVIEW

**Comment by xmulligan** [comment]
@leecalcote is this PR ok?

**Review by leecalcote — APPROVED** [review]
Thanks much, @xmulligan 👍

**Comment by leecalcote** [comment]
Oh, my goodness. Just look at thee date on this PR. Apologies for the delay, @xmulligan.

**Comment by xmulligan** [comment]
No worries! I'm glad it is merged now. Wasn't perfect until today anyways :)

**Pull request merged**
